/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import login.Login;
/**
 *
 * @author Agil
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        kereta = new javax.swing.JMenu();
        formPesan = new javax.swing.JMenuItem();
        dataPenjualan = new javax.swing.JMenuItem();
        JadwalKereta = new javax.swing.JMenuItem();
        TiketPesawat = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        PenumpangPesawat = new javax.swing.JMenuItem();
        JadwalPesawat = new javax.swing.JMenuItem();
        pengguna = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Selamat Datang Administrator");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        kereta.setText("KERETA");
        kereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keretaActionPerformed(evt);
            }
        });

        formPesan.setText("Form Pemesanan");
        formPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPesanActionPerformed(evt);
            }
        });
        kereta.add(formPesan);

        dataPenjualan.setText("Data Penjualan");
        dataPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPenjualanActionPerformed(evt);
            }
        });
        kereta.add(dataPenjualan);

        JadwalKereta.setText("Jadwal Kereta");
        JadwalKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalKeretaActionPerformed(evt);
            }
        });
        kereta.add(JadwalKereta);

        jMenuBar1.add(kereta);

        TiketPesawat.setText("PESAWAT");

        jMenuItem1.setText("Form Pemesanan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        TiketPesawat.add(jMenuItem1);

        PenumpangPesawat.setText("Data Penjualan");
        PenumpangPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenumpangPesawatActionPerformed(evt);
            }
        });
        TiketPesawat.add(PenumpangPesawat);

        JadwalPesawat.setText("Jadwal Pesawat");
        JadwalPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalPesawatActionPerformed(evt);
            }
        });
        TiketPesawat.add(JadwalPesawat);

        jMenuBar1.add(TiketPesawat);

        pengguna.setText("PENGGUNA");
        pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaMouseClicked(evt);
            }
        });
        jMenuBar1.add(pengguna);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login keluar = new Login();
        keluar.show();
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void keretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keretaActionPerformed
        
    }//GEN-LAST:event_keretaActionPerformed

    private void formPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPesanActionPerformed
        new PemesananKereta().setVisible(true);
        dispose();
    }//GEN-LAST:event_formPesanActionPerformed

    private void dataPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPenjualanActionPerformed
        new PenumpangKereta().setVisible(true);
        dispose();
    }//GEN-LAST:event_dataPenjualanActionPerformed

    private void JadwalKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalKeretaActionPerformed
        new JadwalKereta().setVisible(true);
        dispose();
    }//GEN-LAST:event_JadwalKeretaActionPerformed

    private void penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaMouseClicked
        new Pengguna().setVisible(true);
        dispose();
    }//GEN-LAST:event_penggunaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new PemesananPesawat().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void PenumpangPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenumpangPesawatActionPerformed
        new PenumpangPesawat().setVisible(true);
        dispose();
    }//GEN-LAST:event_PenumpangPesawatActionPerformed

    private void JadwalPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalPesawatActionPerformed
        new JadwalPesawat().setVisible(true);
        dispose();
    }//GEN-LAST:event_JadwalPesawatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JadwalKereta;
    private javax.swing.JMenuItem JadwalPesawat;
    private javax.swing.JMenuItem PenumpangPesawat;
    private javax.swing.JMenu TiketPesawat;
    private javax.swing.JMenuItem dataPenjualan;
    private javax.swing.JMenuItem formPesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu kereta;
    private javax.swing.JButton logout;
    private javax.swing.JMenu pengguna;
    // End of variables declaration//GEN-END:variables
}
