/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import login.Login;
/**
 *
 * @author Agil
 */
public class JadwalKereta extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    
    public static Connection getConnection() {
        Connection conn = null;
        String url = "jdbc:mysql://localhost:3306/01kereta_api";
        String user = "root";
        String password = "";
        try {
            conn = DriverManager.getConnection(url, user, password);
        } catch (SQLException e) {
            System.out.println(e);
        }
        return conn;
    }
    
    
    private DefaultTableModel DftTblModel_barang;
    private String SQL; 
    public void TampilData() {
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("ID KRL");
        DftTblModel_barang.addColumn("NAMA");
        DftTblModel_barang.addColumn("KELAS");
        DftTblModel_barang.addColumn("ASAL");
        DftTblModel_barang.addColumn("TUJUAN");
        DftTblModel_barang.addColumn("BERANGKAT");
        DftTblModel_barang.addColumn("SAMPAI");
        DftTblModel_barang.addColumn("HARGA");
        tableJadwalKereta.setModel(DftTblModel_barang);
        Connection conn = getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from jadwal_kereta";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("id_kereta"),
                    res.getString("nama_kereta"),
                    res.getString("kelas_kereta"),
                    res.getString("asal_kereta"),
                    res.getString("tujuan_kereta"),
                    res.getString("berangkat"),
                    res.getString("sampai"),
                    res.getString("harga_tiket")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * Creates new form JadwalKereta
     */
    public JadwalKereta() {
        initComponents();
        this.TampilData();
        this.autoid();
        inputID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputKelas = new javax.swing.JComboBox<>();
        inputID = new javax.swing.JTextField();
        inputAsal = new javax.swing.JComboBox<>();
        inputTujuan = new javax.swing.JComboBox<>();
        inputBerangkat = new javax.swing.JTextField();
        inputSampai = new javax.swing.JTextField();
        inputHarga = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        inputNama = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJadwalKereta = new javax.swing.JTable();
        cbb_kategori = new javax.swing.JComboBox<>();
        inputCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        admin = new javax.swing.JMenu();
        pengguna = new javax.swing.JMenuItem();
        kembali = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        tiket = new javax.swing.JMenu();
        penumpang = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JADWAL KERETA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setText("ID Kereta");

        jLabel2.setText("Kelas");

        jLabel3.setText("Asal Stasiun");

        jLabel4.setText("Tujuan Stasiun");

        jLabel5.setText("Berangkat");

        jLabel6.setText("Harga");

        jLabel7.setText("Sampai");

        inputKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomi", "Eksekutif", "Bisnis", "Premium", " " }));
        inputKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKelasActionPerformed(evt);
            }
        });

        inputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDActionPerformed(evt);
            }
        });

        inputAsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cicalengka", "Haurpugur", "Rancaekek", "Cimekar", "Kiaracondong", "Cikudapateuh", "Bandung", "Ciroyom", "Cimindi", "Cimahi", "Gadobangkong", "Padalarang" }));

        inputTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cicalengka", "Haurpugur", "Rancaekek", "Cimekar", "Kiaracondong", "Cikudapateuh", "Bandung", "Ciroyom", "Cimindi", "Cimahi", "Gadobangkong", "Padalarang" }));

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        reset.setText("RESET FORM");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama");

        inputNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cibatu", "KRD" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputID)
                            .addComponent(inputKelas, 0, 145, Short.MAX_VALUE)
                            .addComponent(inputAsal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputTujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputBerangkat)
                            .addComponent(inputSampai)
                            .addComponent(inputHarga)
                            .addComponent(inputNama, 0, 145, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputBerangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(edit))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tableJadwalKereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tableJadwalKereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJadwalKeretaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableJadwalKereta);

        cbb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID KRL", "Kelas", "Asal", "Tujuan", "Nama" }));
        cbb_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_kategoriActionPerformed(evt);
            }
        });

        inputCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ADMINISTRATOR");

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        admin.setText("Admin");

        pengguna.setText("Pengguna");
        pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaActionPerformed(evt);
            }
        });
        admin.add(pengguna);

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        admin.add(kembali);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        admin.add(logout);

        jMenuBar1.add(admin);

        tiket.setText("Tiket");
        tiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiketMouseClicked(evt);
            }
        });
        tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiketActionPerformed(evt);
            }
        });
        jMenuBar1.add(tiket);

        penumpang.setText("Penumpang");
        penumpang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penumpangMouseClicked(evt);
            }
        });
        penumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penumpangActionPerformed(evt);
            }
        });
        jMenuBar1.add(penumpang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbb_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari)
                            .addComponent(refresh)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void autoid(){
       try{
            Connection conn = getConnection();
            String sql = "SELECT COUNT(id_kereta) as inputID FROM jadwal_kereta";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                String kode = rs.getString("inputID");
                int a = Integer.parseInt(kode);
                int b = a+1;
                inputID.setText("1291"+b);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        try {
            Connection conn = getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into jadwal_kereta(id_kereta, nama_kereta, kelas_kereta, asal_kereta, tujuan_kereta, berangkat, sampai, harga_tiket) values(?,?,?,?,?,?,?,?)");
            stmt.setString(1, inputID.getText());
            stmt.setString(2, (String)inputNama.getSelectedItem());
            stmt.setString(3, (String)inputKelas.getSelectedItem());
            stmt.setString(4, (String)inputAsal.getSelectedItem());
            stmt.setString(5, (String)inputTujuan.getSelectedItem());
            stmt.setString(6, inputBerangkat.getText());
            stmt.setString(7, inputSampai.getText());
            stmt.setString(8, inputHarga.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void tableJadwalKeretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJadwalKeretaMouseClicked
        int baris = tableJadwalKereta.getSelectedRow();
        inputID.setText(DftTblModel_barang.getValueAt(baris, 0).toString());
        inputNama.setSelectedItem(DftTblModel_barang.getValueAt(baris, 1).toString());
        inputKelas.setSelectedItem(DftTblModel_barang.getValueAt(baris, 2).toString());
        inputAsal.setSelectedItem(DftTblModel_barang.getValueAt(baris, 3).toString());
        inputTujuan.setSelectedItem(DftTblModel_barang.getValueAt(baris, 4).toString());
        inputBerangkat.setText(DftTblModel_barang.getValueAt(baris, 5).toString());
        inputSampai.setText(DftTblModel_barang.getValueAt(baris, 6).toString());
        inputHarga.setText(DftTblModel_barang.getValueAt(baris, 7).toString());
    }//GEN-LAST:event_tableJadwalKeretaMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            Connection conn = getConnection();
            PreparedStatement stmt = conn.prepareStatement("update jadwal_kereta set nama_kereta=?,kelas_kereta=?, asal_kereta=?, tujuan_kereta=?, berangkat=?, sampai=?, harga_tiket=? where id_kereta=?");
            stmt.setString(1, (String)inputNama.getSelectedItem());
            stmt.setString(2, (String)inputKelas.getSelectedItem());
            stmt.setString(3, (String)inputAsal.getSelectedItem());
            stmt.setString(4, (String)inputTujuan.getSelectedItem());
            stmt.setString(5, inputBerangkat.getText());
            stmt.setString(6, inputSampai.getText());
            stmt.setString(7, inputHarga.getText());
            stmt.setString(8, inputID.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        Connection conn = getConnection();
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data tersebut?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            try {
                java.sql.PreparedStatement stmt = conn.prepareStatement("delete from jadwal_Kereta where id_kereta ='" + inputID.getText() + "'");
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                TampilData();
                inputID.setText("");
                inputNama.setSelectedItem("");
                inputKelas.setSelectedItem("");
                inputAsal.setSelectedItem("");
                inputTujuan.setSelectedItem("");
                inputBerangkat.setText("");
                inputSampai.setText("");
                inputHarga.setText("");
                inputID.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data gagal di hapus" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        inputID.setText("");
        inputNama.setSelectedItem("");
        inputKelas.setSelectedItem("");
        inputAsal.setSelectedItem("");
        inputTujuan.setSelectedItem("");
        inputBerangkat.setText("");
        inputSampai.setText("");
        inputHarga.setText("");
        inputCari.setText("");
        inputID.requestFocus();
    }//GEN-LAST:event_resetActionPerformed

    private void penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaActionPerformed
        new Pengguna().setVisible(true);
        dispose();
    }//GEN-LAST:event_penggunaActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login keluar = new Login();
        keluar.show();
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiketActionPerformed
        new PemesananKereta().setVisible(true);
        dispose();
    }//GEN-LAST:event_tiketActionPerformed

    private void penumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penumpangActionPerformed
               
    }//GEN-LAST:event_penumpangActionPerformed

    private void penumpangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penumpangMouseClicked
        new PenumpangKereta().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_penumpangMouseClicked

    private void tiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiketMouseClicked
        new PemesananKereta().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_tiketMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("ID KRL");
        DftTblModel_barang.addColumn("NAMA");
        DftTblModel_barang.addColumn("KELAS");
        DftTblModel_barang.addColumn("ASAL");
        DftTblModel_barang.addColumn("TUJUAN");
        DftTblModel_barang.addColumn("BERANGKAT");
        DftTblModel_barang.addColumn("SAMPAI");
        DftTblModel_barang.addColumn("HARGA");
        tableJadwalKereta.setModel(DftTblModel_barang);
        Connection conn = getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            if(cbb_kategori.getSelectedItem().equals("Kelas")){
                SQL = "select * from jadwal_kereta where kelas_kereta like '%"+ inputCari.getText() +"%'";
                System.out.println(SQL);
            }else if(cbb_kategori.getSelectedItem().equals("Asal")){
                SQL = "select * from jadwal_kereta where asal_kereta like '%"+ inputCari.getText() +"%'";
                System.out.println(SQL);
            }else if(cbb_kategori.getSelectedItem().equals("ID KRL")){
                SQL = "select * from jadwal_kereta where id_kereta like '%"+ inputCari.getText() +"%'";
                System.out.println(SQL);
            }else if(cbb_kategori.getSelectedItem().equals("Nama")){
                SQL = "select * from jadwal_kereta where nama_kereta like '%"+ inputCari.getText() +"%'";
                System.out.println(SQL);
            }else {
                 SQL = "select * from jadwal_kereta where tujuan like '%"+ inputCari.getText() +"%'";
                 System.out.println(SQL);
            }
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("id_kereta"),
                    res.getString("nama_kereta"),
                    res.getString("kelas_kereta"),
                    res.getString("asal_kereta"),
                    res.getString("tujuan_kereta"),
                    res.getString("berangkat"),
                    res.getString("sampai"),
                    res.getString("harga_tiket")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnCariActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        this.TampilData();
        inputCari.setText("");
    }//GEN-LAST:event_refreshActionPerformed

    private void inputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDActionPerformed
        autoid();
    }//GEN-LAST:event_inputIDActionPerformed

    private void cbb_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_kategoriActionPerformed
         
    }//GEN-LAST:event_cbb_kategoriActionPerformed

    private void inputCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCariActionPerformed
         
    }//GEN-LAST:event_inputCariActionPerformed

    private void inputKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            Connection c = JadwalKereta.getConnection();
            System.out.println(String.format("berhasil terhubung ke database %s.", c.getCatalog()));
        } catch (SQLException e) {
            System.out.println(e);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadwalKereta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu admin;
    private javax.swing.JButton btnCari;
    private javax.swing.JComboBox<String> cbb_kategori;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JComboBox<String> inputAsal;
    private javax.swing.JTextField inputBerangkat;
    private javax.swing.JTextField inputCari;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputID;
    private javax.swing.JComboBox<String> inputKelas;
    private javax.swing.JComboBox<String> inputNama;
    private javax.swing.JTextField inputSampai;
    private javax.swing.JComboBox<String> inputTujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem kembali;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem pengguna;
    private javax.swing.JMenu penumpang;
    private javax.swing.JButton refresh;
    private javax.swing.JButton reset;
    private javax.swing.JTable tableJadwalKereta;
    private javax.swing.JButton tambah;
    private javax.swing.JMenu tiket;
    // End of variables declaration//GEN-END:variables
}
