/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costumer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import login.Login;
/**
 *
 * @author Agil
 */
public class JadwalPesawat extends javax.swing.JFrame {
    
    public static Connection getConnection() {
        Connection conn = null;
        String url = "jdbc:mysql://localhost:3306/01kereta_api";
        String user = "root";
        String password = "";
        try {
            conn = DriverManager.getConnection(url, user, password);
        } catch (SQLException e) {
            System.out.println(e);
        }
        return conn;
    }
    
    
    private DefaultTableModel DftTblModel_barang;
    private String SQL; 
    public void TampilData() {
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("ID PSW");
        DftTblModel_barang.addColumn("MASKAPAI");
        DftTblModel_barang.addColumn("KELAS");
        DftTblModel_barang.addColumn("ASAL");
        DftTblModel_barang.addColumn("TUJUAN");
        DftTblModel_barang.addColumn("BERANGKAT");
        DftTblModel_barang.addColumn("SAMPAI");
        DftTblModel_barang.addColumn("HARGA");
        tableJadwalPesawat.setModel(DftTblModel_barang);
        Connection conn = getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from jadwal_pesawat";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("id_pesawat"),
                    res.getString("maskapai"),
                    res.getString("kelas_pesawat"),
                    res.getString("asal_pesawat"),
                    res.getString("tujuan_pesawat"),
                    res.getString("berangkat"),
                    res.getString("sampai"),
                    res.getString("harga_tiket")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * Creates new form Jadwalpesawat
     */
    public JadwalPesawat() {
        initComponents();
        this.TampilData();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJadwalPesawat = new javax.swing.JTable();
        kategori = new javax.swing.JComboBox<>();
        inputCari = new javax.swing.JTextField();
        Cari = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        PesanTiket = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        kembali = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JADWAL PESAWAT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        tableJadwalPesawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(tableJadwalPesawat);

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID PSW", "Maskapai", "Kelas", "Asal", "Tujuan" }));

        Cari.setText("Cari Pesawat");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        PesanTiket.setText("Pesan Tiket Pesawat");
        PesanTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanTiketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(PesanTiket)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cari)
                    .addComponent(refresh)
                    .addComponent(PesanTiket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kembali.setText("Kembali");
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        jMenuBar1.add(kembali);

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("ID PSW");
        DftTblModel_barang.addColumn("MASKAPAI");
        DftTblModel_barang.addColumn("KELAS");
        DftTblModel_barang.addColumn("ASAL");
        DftTblModel_barang.addColumn("TUJUAN");
        DftTblModel_barang.addColumn("BERANGKAT");
        DftTblModel_barang.addColumn("SAMPAI");
        DftTblModel_barang.addColumn("HARGA");
        tableJadwalPesawat.setModel(DftTblModel_barang);
        Connection conn = getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            if(kategori.getSelectedItem().equals("Kelas")){
                SQL = "select * from jadwal_pesawat where kelas_pesawat like '%"+ inputCari.getText() +"%'";
                System.out.println(SQL);
            }else if(kategori.getSelectedItem().equals("Asal")){
                SQL = "select * from jadwal_pesawat where asal_pesawat like '%"+ inputCari.getText() +"%'";
                System.out.println(SQL);
            }else if(kategori.getSelectedItem().equals("ID PSW")){
                SQL = "select * from jadwal_pesawat where id_pesawat like '%"+ inputCari.getText() +"%'";
                System.out.println(SQL);
            }else if(kategori.getSelectedItem().equals("Nama")){
                SQL = "select * from jadwal_pesawat where maskapai like '%"+ inputCari.getText() +"%'";
                System.out.println(SQL);
            }else {
                 SQL = "select * from jadwal_pesawat where tujuan like '%"+ inputCari.getText() +"%'";
                 System.out.println(SQL);
            }
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("id_pesawat"),
                    res.getString("maskapai"),
                    res.getString("kelas_pesawat"),
                    res.getString("asal_pesawat"),
                    res.getString("tujuan_pesawat"),
                    res.getString("berangkat"),
                    res.getString("sampai"),
                    res.getString("harga_tiket")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_CariActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        this.TampilData();
    }//GEN-LAST:event_refreshActionPerformed

    private void PesanTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanTiketActionPerformed
        new PemesananKereta().setVisible(true);
        dispose();
    }//GEN-LAST:event_PesanTiketActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        new Costumer().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login keluar = new Login();
        keluar.show();
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalPesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalPesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalPesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalPesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadwalPesawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JButton PesanTiket;
    private javax.swing.JTextField inputCari;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JMenu kembali;
    private javax.swing.JMenu logout;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tableJadwalPesawat;
    // End of variables declaration//GEN-END:variables
}
